"""10

Revision ID: 4eb3dedac162
Revises: d6d002cdaa25
Create Date: 2024-08-28 09:53:36.985752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb3dedac162'
down_revision: Union[str, None] = 'd6d002cdaa25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperatures', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("constraint_cascade_on_delete", 'cities', ['city_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperatures', schema=None) as batch_op:
        batch_op.drop_constraint("constraint_cascade_on_delete", type_='foreignkey')
        batch_op.create_foreign_key("constraint_cascade_on_delete", 'cities', ['city_id'], ['id'])

    # ### end Alembic commands ###
